version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  inventory-service:
    image: quay.io/novelnest/inventory-service:latest
    # build: .
    container_name: inventory-service
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./prisma:/app/prisma
    networks:
      - app_network
